// Generated from tokens.css by scripts/theme-tokens.mjs. Do not edit.

/** Every token of tokens.css as a string, by name without the leading dashes, per theme. */
export const themeTokens = {
	light: {
		'bg': "#f3f4f6",
		'card': "#ffffff",
		'card-alt': "#f8f9fa",
		'fg': "#1c2330",
		'muted': "#5f6b7a",
		'border': "#d8dde3",
		'border-strong': "#8a94a0",
		'accent': "#1f4f8f",
		'accent-hover': "#183f73",
		'accent-subtle': "#e7eef7",
		'accent-fg': "#ffffff",
		'up': "#1d7a4c",
		'up-subtle': "#e6f2ec",
		'up-fg': "#ffffff",
		'down': "#b4322c",
		'down-subtle': "#f8e9e8",
		'down-fg': "#ffffff",
		'warn': "#8a5d00",
		'warn-subtle': "#fbf3e0",
		'chart-1': "#1f4f8f",
		'chart-2': "#c2477a",
		'chart-3': "#b7791f",
		'chart-4': "#0c8a7b",
		'chart-5': "#8a4fb0",
		'sidebar-bg': "#1e2733",
		'sidebar-fg': "#aeb8c5",
		'sidebar-heading': "#8693a3",
		'sidebar-border': "#2b3644",
		'sidebar-active-bg': "#2b3a4d",
		'sidebar-active-fg': "#ffffff",
		'sidebar-active-bar': "#6d9fd8",
		'sidebar-hover-bg': "#25303e",
		'space-unit': "0.25rem",
		'space-0-5': "calc(var(--space-unit) * 0.5)",
		'space-1': "var(--space-unit)",
		'space-1-5': "calc(var(--space-unit) * 1.5)",
		'space-2': "calc(var(--space-unit) * 2)",
		'space-2-5': "calc(var(--space-unit) * 2.5)",
		'space-3': "calc(var(--space-unit) * 3)",
		'space-3-5': "calc(var(--space-unit) * 3.5)",
		'space-4': "calc(var(--space-unit) * 4)",
		'space-5': "calc(var(--space-unit) * 5)",
		'space-6': "calc(var(--space-unit) * 6)",
		'space-7': "calc(var(--space-unit) * 7)",
		'space-8': "calc(var(--space-unit) * 8)",
		'space-10': "calc(var(--space-unit) * 10)",
		'space-12': "calc(var(--space-unit) * 12)",
		'text-2xs': "0.7rem",
		'text-xs': "0.75rem",
		'text-sm': "0.85rem",
		'text-md': "0.9375rem",
		'text-lg': "1.1rem",
		'text-xl': "1.35rem",
		'text-2xl': "1.75rem",
		'text-3xl': "2.2rem",
		'radius': "4px",
		'radius-sm': "3px",
		'radius-lg': "6px",
		'radius-full': "9999px",
		'tab-bar-min-height': "3.5rem",
		'tab-pill-min-height': "4rem",
		'tab-bar-height': "var(--tab-bar-min-height)",
		'font-sans': "'IBM Plex Sans', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
		'font-mono': "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
	},
	dark: {
		'bg': "#12161c",
		'card': "#1a2029",
		'card-alt': "#1f2631",
		'fg': "#e2e6eb",
		'muted': "#8d98a7",
		'border': "#2b3340",
		'border-strong': "#636f81",
		'accent': "#5b8fd0",
		'accent-hover': "#74a2da",
		'accent-subtle': "#1f2d40",
		'accent-fg': "#0e141c",
		'up': "#3fa874",
		'up-subtle': "#16291f",
		'up-fg': "#0e141c",
		'down': "#de6a63",
		'down-subtle': "#321b1a",
		'down-fg': "#0e141c",
		'warn': "#d9a441",
		'warn-subtle': "#30271a",
		'chart-1': "#5b8fd0",
		'chart-2': "#d0628f",
		'chart-3': "#b98526",
		'chart-4': "#23998a",
		'chart-5': "#9f7ed6",
		'sidebar-bg': "#0e1217",
		'sidebar-fg': "#9aa5b3",
		'sidebar-heading': "#7d8999",
		'sidebar-border': "#1d242e",
		'sidebar-active-bg': "#1d2735",
		'sidebar-active-fg': "#ffffff",
		'sidebar-active-bar': "#5b8fd0",
		'sidebar-hover-bg': "#161c24",
		'space-unit': "0.25rem",
		'space-0-5': "calc(var(--space-unit) * 0.5)",
		'space-1': "var(--space-unit)",
		'space-1-5': "calc(var(--space-unit) * 1.5)",
		'space-2': "calc(var(--space-unit) * 2)",
		'space-2-5': "calc(var(--space-unit) * 2.5)",
		'space-3': "calc(var(--space-unit) * 3)",
		'space-3-5': "calc(var(--space-unit) * 3.5)",
		'space-4': "calc(var(--space-unit) * 4)",
		'space-5': "calc(var(--space-unit) * 5)",
		'space-6': "calc(var(--space-unit) * 6)",
		'space-7': "calc(var(--space-unit) * 7)",
		'space-8': "calc(var(--space-unit) * 8)",
		'space-10': "calc(var(--space-unit) * 10)",
		'space-12': "calc(var(--space-unit) * 12)",
		'text-2xs': "0.7rem",
		'text-xs': "0.75rem",
		'text-sm': "0.85rem",
		'text-md': "0.9375rem",
		'text-lg': "1.1rem",
		'text-xl': "1.35rem",
		'text-2xl': "1.75rem",
		'text-3xl': "2.2rem",
		'radius': "4px",
		'radius-sm': "3px",
		'radius-lg': "6px",
		'radius-full': "9999px",
		'tab-bar-min-height': "3.5rem",
		'tab-pill-min-height': "4rem",
		'tab-bar-height': "var(--tab-bar-min-height)",
		'font-sans': "'IBM Plex Sans', ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
		'font-mono': "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
	}
} as const;

export type ThemeTokenName = keyof typeof themeTokens.light;
